name: Docs

on:
  pull_request:
  push:
    branches:    
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2

    - name: Build
      run: |
        python -m pip install -e .[docs]
        sphinx-build docs dist/site -b dirhtml -a

    - name: Publish
      if: ${{ github.event_name == 'push' && github.ref_name == 'main' }}
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: dist/site

